all:
	g++ Arazi_modified.cpp -o object_files/prog_num1 -fomit-frame-pointer
	g++ Arazi_BPV_modified.cpp -o object_files/prog_num2 -fomit-frame-pointer
	g++ BPV-ECDSA_modified.cpp -o object_files/prog_num3 -fomit-frame-pointer
	g++ ECHMQV_modified.cpp -o object_files/prog_num4 -fomit-frame-pointer
	g++ ECHMQV_BPV_modified.cpp -o object_files/prog_num5 -fomit-frame-pointer
	g++ TableGenerate_modified.cpp -o object_files/prog_num6 -fomit-frame-pointer
	g++ ECIES_modified.cpp -o object_files/prog_num7 -fomit-frame-pointer
	g++ ECIES_BPV_modified.cpp -o object_files/prog_num8 -fomit-frame-pointer
	g++ ECIES_DBPV_modified.cpp -o object_files/prog_num9 -fomit-frame-pointer
	g++ Signcryption_modified.cpp -o object_files/prog_num10 -fomit-frame-pointer
	g++ Signcryption_DBPV_modified.cpp -o object_files/prog_num11 -fomit-frame-pointer

prog1:
	./prog_num1

prog2:
	./prog_num2

prog3:
	./prog_num3

prog4:
	./prog_num4

prog5:
	./prog_num5

prog6:
	./prog_num6

#prog7:
	#./prog_num7

#prog8:
	#./prog_num8

#prog9:
	#./prog_num9

#prog10:
	#./prog_num10

#prog11:
	#./prog_num11


clean:
	rm -f prog_num*
